##############################
# Please edit this line to "lucifer_probot" to make the bot run
lucifer_explain_config: Ahhhhhhhhhhh i am not blind so i'll follow what the line above me asked"
##############################  
bot_token: "1468813792:AAHK7dpxm6qlxwF-LYpjAF4rS0X5qnjii4U" 
owner_id: "920437078"  # If you dont know, run the bot and do /id in your private chat with it
api_key: '1493267'  #Owner API Key
api_hash: 'bce3f77245c8baec1fbca82304f11c4f'  #API HASH
owner_username:  "@anonyindian"  #Just write it with the @ ex "@Amazers_xD"
donation_link: "" #paypal etc
support_chat: "@AngelinaSupport" # Your telegram support chat username, must have the "@" Example: @MyBotSupportGroupChat
database_url: "sqldbtype://username:pw@hostname:port/db_name" # needed for any database modules
message_dump: "None" # needed to make sure 'save from' messages persist
gban_dump: "None" #Channel ID here with the hyphen like -123456789
load: []
no_load: ['translation', 'rss', 'cleaner', 'feds']
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: True
del_cmds: False
strict_gban: True
spammers_lists: [100]
ban_sticker: '' #Preferred Ban sticker btw Ban sticker is disabled :)
whitelist_chats: []
blacklist_chats: []



# API SETUP
cash_api: DV2BL3SFET679CAR # Get one from https://www.alphavantage.co/support/#api-key  
time_api: XW2A5QETZF44 # Get one from https://timezonedb.com/register
wall_api: 224033ba3c6b01b9a7daacb0677684c6 # Get one from https://wall.alphacoders.com/api.php
lydia_api: None # Coffeehouse chatbot api key, get one from https://coffeehouse.intellivoid.info/
sw_api: None # Get one from t.me/SitiSchu
api_openweather: None # Get one from https://openweather.com

# Permission
dev_users: [920437078]
sudo_users: [920437078]
support_users: [920437078]
whitelist_users: [920437078]
